# Generated by Django 3.1.3 on 2021-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='descriere',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='locatie',
            field=models.TextField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='nrtel',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10, null=True),
        ),
    ]
