# Generated by Django 3.1.3 on 2021-04-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicii', '0002_auto_20210420_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='judet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='servicii.judet'),
        ),
    ]
